Fortran Modules done
AgriculturalModelExchangeInitiative/SQ_Wheat_Phenology pull request #5
Opened 2018-12-13 00:41 UTC by cyrillemidingoyi

Some Crop modules shared by DSSAT on its'github repository are implemented  in  fortran 90. So, I write the modules in this version #1

2018-12-13 08:22 UTC, pradal requested changes
Mainly the first problem I saw is a problem of consistent coding style:
- use line break consistently (after a subroutine, after end if ot whatever else position
- Naming convention should also be consistent
- DO END DO or IF END IF also need consistency

2018-12-13 08:22 UTC, pradal commented on src/f90/IsMomentRegistredZC_39.f90
> +        if (ANY(calendarMoments=="FlagLeafLiguleJustVisible"))then
Add a space before then

2018-12-13 08:22 UTC, pradal commented on src/f90/VernalizationProgress.f90
> +
Why an empty line?

2018-12-13 08:22 UTC, pradal commented on src/f90/VernalizationProgress.f90
> +
Remove empty line in the if statement

2018-12-13 08:22 UTC, pradal commented on src/f90/crop2mlModules.f90
> +        DO iterator= 1, size(vectorElem)
IF and ENDIF here are uppercase while before (other file) it was lower case.
Be consistent in your style.

2018-12-13 08:22 UTC, pradal commented on src/f90/crop2mlModules.f90
> +        DO iterator= 1, size(vectorElem)
The same for DO & al.

2018-12-13 08:22 UTC, pradal commented on src/f90/leafNumber.f90
> +    !use crop2mlModules
Is it a standard way to call external libs in Crop2ML or just a transient hack?

2018-12-13 08:22 UTC, pradal commented on src/f90/updatePhase.f90
> +        if ((phase1 >= 0) .AND. (phase1 < 1))then
add space before then

2018-12-13 08:22 UTC, pradal commented on src/f90/updatePhase.f90
> +            if ((IsVernalizable==1 .AND. Vernaprog >= 1) .OR. (IsVernalizable==0)) then
remove blank line

2018-12-13 08:22 UTC, pradal commented on src/f90/updatePhase.f90
> +            if ((IsVernalizable==1 .AND. Vernaprog >= 1) .OR. (IsVernalizable==0)) then
or add them in a consistent way

2018-12-13 08:22 UTC, pradal commented on src/f90/updatePhase.f90
> +            if (IgnoreGrainMaturation .eqv. .TRUE.) then
Some variables have the first char uppercase (IgnoreGrainMaturation) other lowercase (cumulTTFromZC).
Need consistency

2018-12-13 08:22 UTC, pradal commented on test/f90/VernalizationProgress.f90
> +    subroutine calculateVernalizationProgress( DayLength, DeltaTT, cumulTT, &
Here subroutine began with lowercase

2018-12-13 08:22 UTC, pradal commented on test/f90/crop2mlModules.f90
> +module crop2mlModules
Duplicated file from src...
Perhaps copy the files before testing but not two same file in git

2018-12-14 12:28 UTC, cyrillemidingoyi commented on src/f90/crop2mlModules.f90
> +        DO iterator= 1, size(vectorElem)
No difference in fortran but I can change it at the same

2018-12-14 12:28 UTC, cyrillemidingoyi commented on src/f90/leafNumber.f90
> +    !use crop2mlModules
yes, it is a standard way, but here I comment this line ("!") to show that some external libs are used in this module

2018-12-14 12:28 UTC, cyrillemidingoyi commented on src/f90/updatePhase.f90
> +            if (IgnoreGrainMaturation .eqv. .TRUE.) then
I didn't change the name of variables in the original Sirius Model

2018-12-17 16:21 UTC, merged